simple_blog/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/', views.EditUserProfile.as_view(), name='profile'),

    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
]

simple_blog/game_blog/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf.urls.static import static

from . import views


urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    path('about/', views.AboutPage.as_view(), name='about'),

    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('posts/', include('posts.urls', namespace='posts')),

    path('ckeditor', include('ckeditor_uploader.urls'))

]

if settings.USE_S3:
    pass
else:
    urlpatterns += (
            static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
            static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

handler400 = 'game_blog.views.error_400_view'
handler403 = 'game_blog.views.error_403_view'
handler404 = 'game_blog.views.error_404_view'
handler500 = 'game_blog.views.error_500_view'

simple_blog/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('drafts/', views.DraftListView.as_view(), name='drafts'),
    path('drafts/<slug>/', views.DraftDetail.as_view(), name='draft'),
    path('drafts/<slug>/publish/', views.PostPublish.as_view(), name='publish'),
    path('drafts/<slug>/edit/', views.UpdateDraft.as_view(), name='edit_draft'),

    path('search/', views.SearchPostView.as_view(), name='search_post'),

    path('new/', views.CreatePost.as_view(), name='create'),

    path('comments/<int:pk>/delete/', views.DeleteComment.as_view(), name='comment_remove'),

    path('delete/', views.DeletePostList.as_view(), name='delete_list'),

    path('<slug>/', views.PostDetail.as_view(), name='single'),
    path('<slug>/delete/', views.DeletePost.as_view(), name='delete'),
    path('<slug>/edit/', views.UpdatePost.as_view(), name='edit'),
]

simple_blog/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import (User, AbstractUser, BaseUserManager, AbstractBaseUser,
                                        PermissionsMixin, Permission)


class CustomUserManager(BaseUserManager):
    """Manager for CustomUser model."""
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have a username")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password
        )
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True

        user.save(using=self._db)
        return user


def get_default_profile_pic():
    return 'images/profile_pics/default_profile_pics/profile_pic.jpg'


class CustomUser(AbstractUser, PermissionsMixin):
    """Extended django User."""

    # required fields
    email = models.EmailField(verbose_name='email', max_length=60, unique=True)
    username = models.CharField(verbose_name='username', max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(verbose_name='is user an admin', default=False)
    is_active = models.BooleanField(verbose_name='is user active', default=True)
    is_staff = models.BooleanField(verbose_name='is staff', default=False)
    is_superuser = models.BooleanField(verbose_name='is user a superuser', default=False)

    # login parameter
    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    def get_all_permissions(self, obj=None):
        if self.is_superuser:
            return Permission.objects.all()
        return Permission.objects.filter(group__user=self)

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        if perm in self.get_all_permissions() or perm in self.get_group_permissions():
            return True
        return False

    def has_module_perms(self, app_label):
        return True


class Profile(models.Model):
    """User's profile."""

    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile',  on_delete=models.CASCADE)
    first_name = models.CharField(verbose_name="first name", max_length=40, null=True, blank=True)
    last_name = models.CharField(verbose_name="last name", max_length=40, null=True, blank=True)
    bio = models.TextField(verbose_name="biography", null=True, blank=True)
    profile_pic = models.ImageField(verbose_name="profile picture", null=True, blank=True,
                                    upload_to='images/profile_pics/', default=get_default_profile_pic)
    uplay_nickname = models.CharField(verbose_name="uplay nickname", max_length=60, null=True, blank=True, unique=True)

    def __str__(self):
        return f"Name: {self.last_name} {self.first_name}"

    @property
    def profile_pic_url(self):
        return str(self.profile_pic)[1:]

    def get_profile_pic_filename(self):
        return str(self.profile_pic)[str(self.profile_pic).index(f'profile_pics/{self.pk}/'):]

simple_blog/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser, Profile


class CustomUserCreateForm(UserCreationForm):
    """Form for creating new users."""
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = CustomUser

    def __init__(self, *args, **kwargs):
        super(CustomUserCreateForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Create a username'
        self.fields['email'].label = 'Email address'


class ProfileUpdateForm(forms.ModelForm):
    """Form for updating user's profile."""
    class Meta:
        model = Profile
        fields = ('bio', 'profile_pic', 'uplay_nickname')

        widgets = {
            'bio': forms.Textarea(attrs={'class': 'input_field'}),
            'uplay_nickname': forms.TextInput(attrs={'class': 'input_field'}),
        }

    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)

        self.fields['bio'].label = 'Write something about experience with Anno series'
        self.fields['profile_pic'].label = 'Upload your profile picture'
        self.fields['uplay_nickname'].label = 'Enter your Uplay nickname'

simple_blog/accounts/views.py
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import CustomUserCreateForm, ProfileUpdateForm
from .models import Profile
from .decorators import restrict_authenticated_users


class SignUp(CreateView):
    """User-Signup view."""
    form_class = CustomUserCreateForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/signup.html'

    @restrict_authenticated_users
    def get(self, request, *args, **kwargs):
        return super(SignUp, self).get(request, *args, **kwargs)


class LoginView(auth_views.LoginView):
    """User-Login view."""
    template_name = 'accounts/login.html'

    @restrict_authenticated_users
    def get(self, request, *args, **kwargs):
        return super(LoginView, self).get(request, *args, **kwargs)


class EditUserProfile(LoginRequiredMixin, UpdateView):
    """Update profile view."""
    model = Profile
    form_class = ProfileUpdateForm
    template_name = 'accounts/profile_update.html'
    context_object_name = 'profile'
    success_url = reverse_lazy('accounts:profile')

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_initial(self):
        return {
            'bio': self.request.user.profile.bio,
            'profile_pic': self.request.user.profile.profile_pic,
            'uplay_nickname': self.request.user.profile.uplay_nickname,
        }

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user.profile = self.request.user.profile
        self.object.save()
        return super(EditUserProfile, self).form_valid(form)

simple_blog/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
<div class="container">
    <h1>Login</h1>

    <form method="POST" class="form login_form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button type="submit" class="btn btn-primary">Login</button>
        {% endbuttons %}

        <a href="{% url 'accounts:password_reset' %}" class="auth_link">Forgot Password?</a>
    </form>
</div>
{% endblock %}

simple_blog/accounts/templates/accounts/password_change.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
    Blog | Change Password
{% endblock %}


{% block content %}
    <div class="container">
        <h1>Change Password</h1>

        <form method="POST" class="form login_form">
            {% csrf_token %}
            {% bootstrap_form form %}

            {% buttons %}
                <button type="submit" class="btn btn-primary">Change Password</button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

simple_blog/accounts/templates/accounts/password_change_done.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
    Blog | Change Password
{% endblock %}


{% block content %}
    <div class="container">
        <h1>Password was changed!</h1>
        <p class="m-auto">

            Your password has been set. You may go ahead and <a href="{% url 'accounts:login' %}">log in</a> now.
        </p>
    </div>
{% endblock %}

simple_blog/accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
    Blog | Reset Password
{% endblock %}


{% block content %}
    <div class="container">
        <h1>Reset your password</h1>
        <p>Forgot your password? Enter an email and we will send you a message with further instructions</p>

        <form method="POST" class="form login_form">
            {% csrf_token %}
            {% bootstrap_form form %}

            {% buttons %}
                <button type="submit" class="btn btn-primary">Reset Password</button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

simple_blog/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
    Blog | Reset Password
{% endblock %}


{% block content %}
    <div class="container">
        <h1>The password has been changed!</h1>
        <p><a href="{% url 'accounts:login' %}" class="auth_link">Log in again?</a></p>
    </div>

{% endblock %}

simple_blog/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
    Blog | Reset Password
{% endblock %}


{% block content %}
    <div class="container">
        {% if validlink %}
            <h1>Password reset</h1>
            <p>Please enter and confirm your new password.</p>
            <form action="" method="post" class="form login_form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Change Password</button>
                {% endbuttons %}
            </form>
        {% else %}
            <h1>Password reset failed</h1>
            <p>
                The password reset link was invalid, possibly because it has already been used.
                Please request a new password reset
            </p>
        {% endif %}
    </div>
{% endblock %}

simple_blog/accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
    Blog | Reset Password
{% endblock %}


{% block content %}
    <div class="container">
        <h1>Password reset sent</h1>
        <p>
            We’ve emailed you instructions for setting your password, if an account exists with the email you entered.
            You should receive them shortly.
        </p>
        <p>
            If you don’t receive an email, please make sure you’ve entered the address you registered with,
            and check your spam folder.
        </p>
    </div>
{% endblock %}

simple_blog/accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

simple_blog/accounts/templates/accounts/profile_detail.html
{% extends 'base.html' %}

{% block title %}
    Blog | Profile
{% endblock %}


{% block content %}
    <h4>Profile</h4>

    <div class="media">
        <div class="media-body">
            {{ profile.user.username }}
            {{ profile.bio }}
            {{ profile.profile_pic }}
            {{ profile.uplay_nickname }}
        </div>
    </div>

{% endblock %}

simple_blog/accounts/templates/accounts/profile_form.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}
    Blog | Profile
{% endblock %}


{% block content %}
    <h4>Edit your profile</h4>
    <form method="POST" id="profileForm" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.media }}
        <button type="submit" class="btn btn-primary btn-large profile_button">Save</button>
    </form>
{% endblock %}

simple_blog/accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
    Blog | Profile
{% endblock %}


{% block content %}
    <h4 class="container">Profile</h4>
    <div class="media container">

        <div class="media-body form-group">
            <form method="POST" id="profileForm" enctype="multipart/form-data">
                {% csrf_token %}
                {%  bootstrap_form form %}
                {{ form.media }}

                <a href="{% url 'accounts:password_change' %}" class="auth_link">Change Password</a>

                {% buttons %}
                    <button id="profileButton" type="submit" class="btn btn-primary btn-large mt-4">Save</button>
                {% endbuttons %}
            </form>
        </div>
    </div>

{% endblock %}

simple_blog/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h1>Sign Up</h1>
  <form method="POST" class="form sign_up_form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Sign Up</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}