simple_blog/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/', views.EditUserProfile.as_view(), name='profile'),

    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
]

simple_blog/game_blog/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf.urls.static import static

from . import views


urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    path('about/', views.AboutPage.as_view(), name='about'),

    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('posts/', include('posts.urls', namespace='posts')),

    path('ckeditor', include('ckeditor_uploader.urls'))

]

if settings.USE_S3:
    pass
else:
    urlpatterns += (
            static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
            static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

handler400 = 'game_blog.views.error_400_view'
handler403 = 'game_blog.views.error_403_view'
handler404 = 'game_blog.views.error_404_view'
handler500 = 'game_blog.views.error_500_view'

simple_blog/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('drafts/', views.DraftListView.as_view(), name='drafts'),
    path('drafts/<slug>/', views.DraftDetail.as_view(), name='draft'),
    path('drafts/<slug>/publish/', views.PostPublish.as_view(), name='publish'),
    path('drafts/<slug>/edit/', views.UpdateDraft.as_view(), name='edit_draft'),

    path('search/', views.SearchPostView.as_view(), name='search_post'),

    path('new/', views.CreatePost.as_view(), name='create'),

    path('comments/<int:pk>/delete/', views.DeleteComment.as_view(), name='comment_remove'),

    path('delete/', views.DeletePostList.as_view(), name='delete_list'),

    path('<slug>/', views.PostDetail.as_view(), name='single'),
    path('<slug>/delete/', views.DeletePost.as_view(), name='delete'),
    path('<slug>/edit/', views.UpdatePost.as_view(), name='edit'),
]

simple_blog/templates/400_page.html
{% extends 'base.html' %}


{% block title %}
    Bad Request
{% endblock %}


{% block content %}
    <div class="container">
        <h1>Something went wrong!</h1>
        <h2>Bad Request</h2>
    </div>
{% endblock %}

simple_blog/templates/403_page.html
{% extends 'base.html' %}


{% block title %}
    Permission Denied
{% endblock %}


{% block content %}
    <div class="container">
        <h1>Something went wrong!</h1>
        <h2>You do not have access to this page</h2>
    </div>
{% endblock %}

simple_blog/templates/404_page.html
{% extends 'base.html' %}


{% block title %}
    Page Not Found
{% endblock %}


{% block content %}
    <div class="container">
        <h1>Something went wrong!</h1>
        <h2>Page not found</h2>
    </div>
{% endblock %}

simple_blog/templates/500_page.html
{% extends 'base.html' %}


{% block title %}
    Server Error
{% endblock %}


{% block content %}
    <div class="container">
        <h1>Something went wrong!</h1>
        <h2>Server Error</h2>
    </div>
{% endblock %}

simple_blog/templates/about.html
{% extends 'base.html' %}

{% block title %}
    Blog | About
{% endblock %}


{% block content %}

    <div class="container">
        <h1 class="text-center">About "Anno Union" clone</h1>
        <p>
            {% if user.is_authenticated %}
                Welcome back, {{ user.username }}
            {% endif %}
        </p>
    </div>

{% endblock %}

simple_blog/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load posts_extras %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>

    <!-- Bootstrap 4 - CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Bootstrap 4 - FontAwesome Icons -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">

    {#    Google Fonts     #}
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Arvo:ital,wght@0,400;0,700;1,400;1,700&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Open+Sans:ital,wght@0,300;0,400;0,600;1,300;1,400&family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

    {#  Custom CSS   #}
    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'game_blog/css/master.css' %}">
</head>

<body class="d-flex flex-column min-vh-100">
    <!--Navbar-->
    <nav class="smart_scroll navbar navbar-expand-lg navbar-light" id="baseNavbar">

        <!-- Navbar brand -->
        <a href="{% url 'homepage' %}" class="navbar-brand">
            <img id="blogLogo" src="{% static 'game_blog/images/anno_union_logo.jpg' %}" alt="Blog Logo">
        </a>


        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

            <!-- Links -->
            <ul class="navbar-nav mr-auto ml-2">
              <li class="nav-item {{ active_homepage }}">
                <a class="nav-link" href="{% url 'homepage' %}">Home</a>
              </li>
              <li class="nav-item {{ active_blog_page }}">
                <a class="nav-link" href="{% url 'posts:all' %}">Blog</a>
              </li>
              <li class="nav-item {{ active_about_page }}">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
            </ul>
            <!-- Links -->
            {% if user.is_authenticated %}
                <ul class="navbar-nav ml-2 pr-3 nav-flex-icons">
                    <li class="nav-item dropdown mt-2">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
                          aria-haspopup="true" aria-expanded="false">
                            {% if user.profile.profile_pic %}
                                <img class="profile_pic" src="{{ user.profile.profile_pic.url }}" alt="User Profile Picture">
                            {% else %}
                                <img class="profile_pic" src="{% static 'game_blog/images/profile_pic.jpg' %}"
                                     alt="Default Profile Picture">
                            {% endif %}
                            Profile
                        </a>

                        <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
                          <a class="dropdown-item" href="{% url 'accounts:profile' %}">My account</a>
                          <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
                        </div>
                    </li>

                        {#      Staff links     #}
                    {% if user.is_staff %}
                        <li class="nav-item dropdown mt-2">
                            <a href="" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">Admin</a>

                            <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
                              <a class="dropdown-item" href="{% url 'posts:create' %}">Create new post</a>
                              <a class="dropdown-item" href="{% url 'posts:drafts' %}">Drafts</a>
                              <a class="dropdown-item" href="{% url 'posts:delete_list' %}">Delete post</a>
                            </div>
                        </li>
                    {% endif %}
                </ul>

            {% else %}
                <ul class="navbar-nav ml-2">
                  <li class="nav-item pr-3">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-item navbar-link nav-link" href="{% url 'accounts:login' %}">Log In</a>
                  </li>
                </ul>
            {% endif %}

            <form class="navbar-form form-inline" method="get" action="{% url 'posts:search_post' %}"
                  role="search" id="navbarSearchForm">
              <div class="md-form my-2">
                <input id="searchBarInput" class="input_field form-control mr-sm-2" name="q"
                       type="text" placeholder="Search" aria-label="Search">
              </div>
            </form>
        </div>
      <!-- Collapsible content -->
    </nav>


    {#    Main Content  #}
    <div id="wrap" class="wrapper flex-grow-1">
        <div id="main" class="container content main_content mt-4 mb-5">
            {% block content %}
            {% endblock %}
        
            {% block pagination %}
                {% if is_paginated %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a tabindex="-1" class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">
                                        Previous
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a tabindex="-1" class="page-link" href="">Previous</a>
                                </li>
                            {% endif %}
                            {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                    <li class="active page-item">
                                        <a class="page-link" href="?{% url_replace page=i %}">{{ i }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link" href="?{% url_replace page=i %}">{{ i }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">Next</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link" href="">Next</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            {% endblock %}
        </div>
    </div>


    {# Footer #}
    <footer class="footer text-center mt-4">
              <!-- Footer Links -->
        <div class="container-fluid text-center text-md-left text-lg-center ">
            <!-- Grid row -->
            <div class="row ">

                <!-- Grid column -->
                <div class="col-md-4">
                    <!--Image-->
                    <div class="">
                        <a href="{% url 'homepage' %}">
                            <img id="footerLogo" src="{% static 'game_blog/images/anno_union_logo.jpg' %}" class="img-fluid" alt="Blog Logo">
                        </a>
                    </div>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-4">

                    <!-- Links -->
                    <ul class="list-unstyled">
                      <li>
                        <a href="{% url 'homepage' %}">Home</a>
                      </li>
                      <li>
                        <a href="{% url 'posts:all' %}">Blog</a>
                      </li>
                    </ul>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-4">

                    <!-- Links -->
                    <ul class="list-unstyled">
                      <li>
                        <a href="{% url 'about' %}">About</a>
                      </li>
                      <li>
                        <a href="mailto:romanreznikov2002@yandex.ru">Contact</a>
                      </li>
                    </ul>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
        <!-- Footer Links -->

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">

        </div>
        <!-- Copyright -->

    </footer>
    {# Footer #}


    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

        {#    Custom JS     #}
    <script src="{% static "game_blog/js/master.js"%}" type="text/javascript" ></script>

    <!-- Bootstrap 4 - JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html>

simple_blog/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Blog | Main Page
{% endblock %}


{% block content %}

{#    <div class="container">#}
{#        <h1 class="text-center">Welcome to the Anno 1800 Blog!</h1>#}
{#    </div>#}

    <div id="carouselPosts" class="carousel slide carousel-fade" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100"
                     src="{% static background_images.0 %}"
                     alt="First slide" href="#">

                <div class="carousel-caption d-none d-md-block">
                    <h5></h5>
                    <p></p>
                </div>
            </div>

            <div class="carousel-item">
                <img class="d-block w-100"
                     src="{% static background_images.1 %}"
                     alt="Second slide" href="#">
                <div class="carousel-caption d-none d-md-block">
                    <h5></h5>
                    <p></p>
                </div>
            </div>

            <div class="carousel-item">
                <img class="d-block w-100" src="{% static background_images.2 %}"
                     alt="Third slide" href="#">
                <div class="carousel-caption d-none d-md-block">
                    <h5></h5>
                    <p></p>
                </div>
            </div>
        </div>

        <a class="carousel-control-prev" href="#carouselPosts" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselPosts" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>


    <div class="container header mt-4">
        <div class="row">
            <div class="col-md-8 mt-4">
                <h1 class="title">Welcome to the Anno Blog!</h1>
            </div>

            <div class="col-md-4 description mt-4">
                <p>
                    Get all the latest news, updates and exclusive behind the scenes looks at Ubisoft
                    Mainz's beloved city-building and strategy franchise ''Anno'', straight from the development team!
                </p>
            </div>
        </div>
    </div>

    <div class="container latest_posts">
        {% if latest_posts %}
                    <h1 class="text-center">Featured Posts</h1>
        <div class="row">
            {% for post in latest_posts %}
                {% if post.published_date %}
                    <div class="col-md-4 col-sm-12 col-xs-12">
                        <div class="card">
                              <a href="{% url 'posts:single' slug=post.slug %}" class="stretched-link"></a>
                              {% if post.header_image %}
                                <img class="card-img-top" src="{{ post.header_image.url }}" alt="Post Header Image">
                              {% endif %}

                              <div class="card-body">
                                <h5 class="card-title">{{ post.title }}</h5>
                                <p class="card-text"></p>
                              </div><!-- card content -->

                              <div class="card-footer">
                                <p class="card-text d-inline">
                                  <small class="text-muted">{{ post.published_date|date:'Y-m-d' }}</small>
                                </p>
                                <i class="fas fa-arrow-right post_arrow_img d-inline"></i>
                              </div>
                          </div><!-- card -->
                    </div>
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
    </div>

{% endblock %}