simple_blog/game_blog/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf.urls.static import static

from . import views


urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    path('about/', views.AboutPage.as_view(), name='about'),

    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('posts/', include('posts.urls', namespace='posts')),

    path('ckeditor', include('ckeditor_uploader.urls'))

]

if settings.USE_S3:
    pass
else:
    urlpatterns += (
            static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
            static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

handler400 = 'game_blog.views.error_400_view'
handler403 = 'game_blog.views.error_403_view'
handler404 = 'game_blog.views.error_404_view'
handler500 = 'game_blog.views.error_500_view'

simple_blog/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('drafts/', views.DraftListView.as_view(), name='drafts'),
    path('drafts/<slug>/', views.DraftDetail.as_view(), name='draft'),
    path('drafts/<slug>/publish/', views.PostPublish.as_view(), name='publish'),
    path('drafts/<slug>/edit/', views.UpdateDraft.as_view(), name='edit_draft'),

    path('search/', views.SearchPostView.as_view(), name='search_post'),

    path('new/', views.CreatePost.as_view(), name='create'),

    path('comments/<int:pk>/delete/', views.DeleteComment.as_view(), name='comment_remove'),

    path('delete/', views.DeletePostList.as_view(), name='delete_list'),

    path('<slug>/', views.PostDetail.as_view(), name='single'),
    path('<slug>/delete/', views.DeletePost.as_view(), name='delete'),
    path('<slug>/edit/', views.UpdatePost.as_view(), name='edit'),
]

simple_blog/posts/models.py
from ckeditor_uploader.fields import RichTextUploadingField

from django import template
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from accounts.models import CustomUser

register = template.Library()


def get_default_header_image():
    return 'images/post_headers/default_post_headers/default_post_header.jpg'


class Post(models.Model):
    """Single post on the website."""
    slug = models.SlugField(verbose_name="slug", allow_unicode=True, unique=True)
    created_date = models.DateTimeField(verbose_name="created date", auto_now=True)
    published_date = models.DateTimeField(verbose_name="published date", blank=True, null=True)
    header_image = models.ImageField(
        verbose_name="header image",
        null=True,
        blank=True,
        upload_to='images/post_headers/',
        default=get_default_header_image
    )
    title = models.CharField(verbose_name="title", max_length=255)
    content = RichTextUploadingField(verbose_name="main content", blank=True, null=True)

    class Meta:
        ordering = ['published_date']

    def __str__(self):
        return f"Title: {self.title}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:draft', kwargs={'slug': self.slug})


class Comment(models.Model):
    """Comment related to a Post."""
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(CustomUser, related_name='comment', on_delete=models.CASCADE)
    text = models.TextField(verbose_name='text of the comment')
    posted_date = models.DateTimeField(verbose_name="posted date", auto_now=True)

    class Meta:
        ordering = ["-posted_date"]

    def __str__(self):
        return f"Author: {self.author}, Text: {self.text}"

simple_blog/posts/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget

from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'header_image', 'content',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'post_title_class input_field'}),
            'content': CKEditorUploadingWidget(),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={'class': 'comment_text_class input_field'}),
        }

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = ''

simple_blog/posts/views.py
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .forms import CommentForm, PostForm
from .models import Post, Comment
from .services import (publish_post, save_comment_from_form, get_published_posts, get_search_results,
                       get_drafts, get_all_posts, get_comment_by_pk, get_post_by_slug)


class PostList(generic.ListView):
    """List posts (paginate by 6)."""
    model = Post
    paginate_by = 6

    def get_queryset(self):
        return get_published_posts()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList, self).get_context_data(**kwargs)
        context['active_blog_page'] = 'active'
        return context


class PostDetail(generic.DetailView):
    """Single post's details."""
    model = Post
    slug_url_kwarg = 'slug'
    query_pk_and_slug = True

    def get_queryset(self):
        return get_published_posts()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)

        form = CommentForm()
        context['form'] = form

        return context

    def post(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            form = CommentForm(data=self.request.POST)
            if form.is_valid():
                save_comment_from_form(form, self.kwargs.get('slug'), self.request.user)
        else:
            return redirect('accounts:login')
        return redirect('posts:single', slug=self.kwargs.get('slug'))


class CreatePost(LoginRequiredMixin,
                 PermissionRequiredMixin,
                 generic.CreateView):
    """Post's creation."""
    model = Post
    permission_required = 'posts.add_post'
    redirect_field_name = 'posts:draft'
    form_class = PostForm

    def form_valid(self, form):
        self.object = form.save()
        return super(CreatePost, self).form_valid(form)


class UpdatePost(LoginRequiredMixin,
                 PermissionRequiredMixin,
                 generic.UpdateView):
    """Edit post."""
    model = Post
    permission_required = 'posts.change_post'
    redirect_field_name = 'posts:single'
    form_class = PostForm

    def get_success_url(self):
        return reverse('posts:single', kwargs={'slug': self.kwargs.get('slug')})


class SearchPostView(generic.ListView):
    """Search results (list of posts)."""
    model = Post
    template_name = 'posts/post_search_results.html'

    def get_queryset(self):
        return get_search_results(self.request.GET.get('q'))


class DeletePost(LoginRequiredMixin,
                 PermissionRequiredMixin,
                 generic.DeleteView):
    """Delete Post."""
    model = Post
    permission_required = 'posts.delete_post'
    redirect_field_name = 'posts:single'
    form_class = PostForm
    success_url = reverse_lazy('posts:all')


class DraftListView(LoginRequiredMixin,
                    PermissionRequiredMixin,
                    generic.ListView):
    """List drafts."""
    model = Post
    permission_required = 'posts.add_post'
    redirect_field_name = 'posts:single'
    context_object_name = 'draft_list'
    template_name = 'posts/draft_list.html'

    def get_queryset(self):
        return get_drafts()


class DeletePostList(LoginRequiredMixin,
                     PermissionRequiredMixin,
                     generic.ListView):
    """List posts that can be deleted."""
    model = Post
    paginate_by = 6
    permission_required = 'posts.delete_post'
    template_name = 'posts/post_delete_list.html'

    def get_queryset(self):
        return get_all_posts()


class DraftDetail(LoginRequiredMixin,
                  PermissionRequiredMixin,
                  generic.DetailView):
    """Single draft detail."""
    model = Post
    permission_required = 'posts.add_post'
    template_name = 'posts/draft_detail.html'
    context_object_name = 'draft'

    def get_queryset(self):
        return get_drafts()


class UpdateDraft(LoginRequiredMixin,
                  PermissionRequiredMixin,
                  generic.UpdateView):
    """Edit draft."""
    model = Post
    permission_required = 'posts.change_post'
    template_name = 'posts/post_form.html'
    redirect_field_name = 'posts:single'
    form_class = PostForm

    def get_success_url(self):
        return reverse('posts:draft', kwargs={'slug': self.kwargs.get('slug')})


class PostPublish(LoginRequiredMixin,
                  PermissionRequiredMixin,
                  generic.DetailView):
    """Publish post."""
    permission_required = 'posts.add_post'
    model = Post
    template_name = 'posts/draft_publish.html'
    context_object_name = 'draft'

    def get_queryset(self):
        return get_drafts()

    def post(self, request, *args, **kwargs):
        try:
            post = get_post_by_slug(self.kwargs.get('slug'))
        except Post.DoesNotExist:
            messages.warning(self.request,
                             "You cannot publish this post, because it does not exist")
        else:
            publish_post(post)
            messages.success(self.request,
                             "You have successfully published this post!")
            return redirect('/posts/')


class DeleteComment(LoginRequiredMixin,
                    PermissionRequiredMixin,
                    generic.DeleteView):
    """Delete comment."""
    model = Comment
    permission_required = 'posts.delete_comment'
    template_name = 'posts/comment_confirm_delete.html'
    context_object_name = 'comment'

    def get_object(self, queryset=None):
        return get_comment_by_pk(self.kwargs.get('pk'))

    def get_success_url(self):
        return reverse_lazy('posts:single',
                            kwargs={'slug': get_comment_by_pk(self.kwargs.get('pk')).post.slug})

simple_blog/posts/templates/posts/_draft.html
{% if draft.header_image %}
    <img class="post_detail_header_image" src="{{ draft.header_image.url }}" alt="Draft Header Image">
{% endif %}
<h1 class="mt-3">{{ draft.title }}</h1>

<p><small>Creation Date: {{ draft.created_date|date:'Y-m-d' }}</small>

<div class="container mb-5 draft_content">
    <p class="mt-5">
        {{ draft.content|safe }}
    </p>
</div>

simple_blog/posts/templates/posts/_post.html
{% if post.header_image %}
    <img class="post_detail_header_image" src="{{ post.header_image.url }}" alt="Post Header Image">
{% endif %}
<h1 class="mt-3">{{ post.title }}</h1>

{% if post.published_date %}
    <p><small>{{ post.published_date|date:'Y-m-d' }}</small>
{% else %}
    <p><small>Creation Date: {{ post.created_date|date:'Y-m-d' }}</small>
{% endif %}

<div class="container mb-5 post_content">
    <p class="mt-5">
        {{ post.content|safe }}
    </p>
</div>

simple_blog/posts/templates/posts/comment_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block title %}
    Blog | Delete Comment
{% endblock %}


{% block post_content %}
    <h3 class="mb-5">Are you sure that you want to delete this comment?</h3>

        <div class="container user_comment mb-5">
            <img class="profile_pic d-inline" src="{{ comment.author.profile.profile_pic.url }}" alt="User Profile Picture">
            <p class="d-inline ml-3">{{ comment.author.username }}</p>
            <p class="mt-3">{{ comment.text|safe }}</p>
            <p><small>{{ comment.posted_date|date:'j.F Y' }}</small></p>
        </div>

    <form class="mt-4" method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
        <a href="{% url 'posts:single' slug=comment.post.slug %}" class="btn btn-light btn-large ml-3">Cancel</a>
    </form>
{% endblock %}

simple_blog/posts/templates/posts/comment_form.html
{% extends 'posts/post_base.html' %}

{% block title %}
    Blog | New Comment
{% endblock %}


{% block post_content %}
    
{% endblock %}

simple_blog/posts/templates/posts/draft_detail.html
{% extends 'posts/post_base.html' %}

{% block title %}
    Blog | Draft Details
{% endblock %}

{% block pre_post %}

{% endblock %}


{% block post_content %}
    {% include "posts/_draft.html" with draft=object hide_delete=True %}

    <form class="mt-5" method="POST">
        {% csrf_token %}
        <a href="{% url 'posts:edit_draft' slug=draft.slug %}" class="btn btn-info btn-lg mr-3">Edit</a>
        <a href="{% url 'posts:publish' slug=draft.slug %}" class="btn btn-warning btn-lg mr-3">Publish</a>
        <a href="{% url 'posts:delete' slug=draft.slug %}" class="btn btn-danger btn-lg mr-3">Delete</a>
    </form>
{% endblock %}

simple_blog/posts/templates/posts/draft_list.html
{% extends 'posts/post_base.html' %}

{% block title %}
    Blog | Drafts
{% endblock %}


{% block post_content %}
    {% if draft_list %}
        <h1>Drafts</h1>

         <div class="container">
             <div class="row">
                {%  for draft in draft_list  %}
                      <div class="col-md-4 col-sm-6 col-xs-12">
                          <div class="card">
                              <a href="{% url 'posts:draft' slug=draft.slug %}" class="stretched-link"></a>
                              {% if draft.header_image %}
                                <img class="card-img-top" src="{{ draft.header_image.url }}" alt="Post Header Image">
                              {% endif %}

                              <div class="card-body">
                                <h5 class="card-title">{{ draft.title }}</h5>
                                <p class="card-text"></p>
                              </div><!-- card content -->

                              <div class="card-footer">
                                <p class="card-text d-inline">
                                  <small class="text-muted">
                                      Creation date:
                                      {{ draft.created_date|date:'Y-m-d' }}
                                  </small>
                                </p>
                                <i class="fas fa-arrow-right post_arrow_img d-inline"></i>
                              </div>
                          </div><!-- card -->
                      </div><!-- col-md-4 -->
                {%  endfor %}
             </div>
         </div><!-- container -->
    {% else %}
        <h1>There are no drafts yet</h1>
    {% endif %}
{% endblock %}

simple_blog/posts/templates/posts/draft_publish.html
{% extends 'posts/post_base.html' %}

{% block title %}
    Blog | Publish Post
{% endblock %}


{% block post_content %}
    <h3 class="mb-5">Are you sure that you want to publish this post?</h3>

    {% include 'posts/_draft.html' with draft=object hide_delete=True %}

    <form class="mt-4" method="POST">
        {% csrf_token %}
        <input type="submit" value="Publish" class="btn btn-warning btn-large">
        <a href="{% url 'posts:draft' slug=draft.slug %}" class="btn btn-light btn-large ml-3">Cancel</a>
    </form>
{% endblock %}

simple_blog/posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block title %}
    Posts Base Title
{% endblock %}


{% block content %}
    <div class="container">
        {% block pre_post %}{% endblock %}
        {% block post_content %}{% endblock %}

        <div class="container mt-5">
             {% block comments_section %}{% endblock %}
        </div>
    </div>
{% endblock %}

simple_blog/posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block title %}
    Blog | Delete Post
{% endblock %}


{% block post_content %}
    <h3 class="mb-5">Are you sure that you want to delete this post?</h3>

    {% include 'posts/_post.html' with post=object hide_delete=True %}

    <form class="mt-4" method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
        {% if post.published_date %}
            <a href="{% url 'posts:single' slug=post.slug %}" class="btn btn-light btn-large ml-3">Cancel</a>
        {% else %}
            <a href="{% url 'posts:draft' slug=post.slug %}" class="btn btn-light btn-large ml-3">Cancel</a>
        {% endif %}
    </form>
{% endblock %}

simple_blog/posts/templates/posts/post_delete_list.html
{% extends 'posts/post_base.html' %}

{% block title %}
    Blog | Posts to delete
{% endblock %}


{% block post_content %}
    {% if post_list %}
         <div class="container">
            <h1>Which post do you want to delete?</h1>

         <div class="container">
            <div class="row">
            {%  for post in post_list  %}

                  <div class="col-md-4 col-sm-6 col-xs-12">
                      <div class="card">
                          <a href="{% url 'posts:delete' slug=post.slug %}" class="stretched-link"></a>
                          {% if post.header_image %}
                            <img class="card-img-top" src="{{ post.header_image.url }}" alt="Post Header Image">
                          {% endif %}

                          <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="card-text"></p>
                          </div><!-- card content -->

                          <div class="card-footer">
                            <p class="card-text d-inline">
                              <small class="text-muted">{{ post.published_date|date:'Y-m-d' }}</small>
                            </p>
                            <i class="fas fa-arrow-right post_arrow_img d-inline"></i>
                          </div>
                      </div><!-- card -->
                  </div><!-- col-md-4 -->
            {%  endfor %}
            </div>
        </div><!-- container -->
    {% else %}
        <h1>There are no posts or drafts yet</h1>
    {% endif %}

{% endblock %}

simple_blog/posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}

{% load bootstrap4 %}

{% block title %}
    Blog | Post Details
{% endblock %}

{% block pre_post %}

{% endblock %}



{% block post_content %}
    {% include "posts/_post.html" with post=object hide_delete=True %}
{% endblock %}


{% block comments_section %}
    <h2>Comments</h2>
    <h4 class="mt-5">Leave a comment</h4>
    <form method="POST" id="comment_form" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button id="commentButton" type="submit" class="btn btn-primary btn-large mb-5">Post Comment</button>
        {% endbuttons %}
    </form>
    {% for comment in post.comments.all %}
        <div class="container user_comment mb-5">
            <img class="profile_pic d-inline" src="{{ comment.author.profile.profile_pic.url }}" alt="User Profile Picture">
            <p class="d-inline ml-3">{{ comment.author.username }}</p>

            {% if user.is_staff %}
                <a href="{% url 'posts:comment_remove' pk=comment.pk %}" class="btn btn-danger btn-sm ml-3 delete_comment">Delete Comment</a>
            {% endif %}


            <p class="mt-3">{{ comment.text|safe }}</p>
            <p class="d-inline mr-3"><small>{{ comment.posted_date|date:'j.F Y' }}</small></p>
        </div>
        {% empty %}
            <p>No comments posted</p>
    {% endfor %}
{% endblock %}

simple_blog/posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}

{% load bootstrap4 %}

{% block title %}
    Blog | New Post
{% endblock %}


{% block post_content %}
<h4>Create New Post</h4>
<form method="POST" id="postForm" enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form %}
    {{ form.media }}
	{% buttons %}
		<button type="submit" id="postCreateButton" class="btn btn-primary btn-large">Save</button>
	{% endbuttons %}
</form>
{% endblock %}

simple_blog/posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}

{% block title %}
    Blog | All Posts
{% endblock %}


{% block post_content %}
    {% if post_list %}
        <div class="container">
        <h1>Posts</h1>
            <div class="row">
            {%  for post in post_list  %}
                  <div class="col-md-4 col-sm-6 col-xs-12">
                      <div class="card">
                          <a href="{% url 'posts:single' slug=post.slug %}" class="stretched-link"></a>
                          {% if post.header_image %}
                            <img class="card-img-top" src="{{ post.header_image.url }}" alt="Post Header Image">
                          {% endif %}

                          <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="card-text"></p>
                          </div><!-- card content -->

                          <div class="card-footer">
                            <p class="card-text d-inline">
                              <small class="text-muted">{{ post.published_date|date:'Y-m-d' }}</small>
                            </p>
                            <i class="fas fa-arrow-right post_arrow_img d-inline"></i>
                          </div>
                      </div><!-- card -->
                  </div><!-- col-md-4 -->
            {%  endfor %}
            </div>
        </div><!-- container -->
    {% else %}
        <h1>There are no posts yet</h1>
    {% endif %}

{% endblock %}

simple_blog/posts/templates/posts/post_search_results.html
{% extends 'posts/post_base.html' %}

{% block title %}
    Blog | All Posts
{% endblock %}


{% block post_content %}
    {% if post_list %}
         <div class="container">
            {%  for post in post_list  %}
                {% if forloop.counter0|divisibleby:3 %}
                <div class="row">
                {%  endif %}
                  <div class="col-md-4">
                      <div class="card">
                          <a href="{% url 'posts:single' slug=post.slug %}" class="stretched-link"></a>
                          {% if post.header_image %}
                            <img class="card-img-top" src="{{ post.header_image.url }}" alt="Post Header Image">
                          {% endif %}

                          <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="card-text"></p>
                          </div><!-- card content -->

                          <div class="card-footer">
                            <p class="card-text d-inline">
                              <small class="text-muted">{{ post.published_date|date:'Y-m-d' }}</small>
                            </p>
                            <i class="fas fa-arrow-right post_arrow_img d-inline"></i>
                          </div>
                      </div><!-- card -->
                  </div><!-- col-md-4 -->
            {%  if forloop.counter|divisibleby:3 or forloop.last %}</div><!-- row closing -->{%  endif %}

            {%  endfor %}
         </div><!-- container -->
    {% else %}
        <h1>Sorry, we couldn't find any results</h1>
    {% endif %}

{% endblock %}